package storage

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/ehabterra/workflow"
)

// SQLiteStorage provides a persistent storage implementation using SQLite.
// It is highly configurable to allow for custom table and column names,
// as well as storing arbitrary application-specific data alongside the
// workflow state.
type SQLiteStorage struct {
	db *sql.DB

	// Configuration for the main workflow state table.
	table       string
	idColumn    string
	stateColumn string

	// CustomFields maps a context key to a database column name and its type.
	// Example: {"document_id": "document_id_col TEXT", "approver": "approver_col TEXT"}
	customFields map[string]string
}

// Option is a function that configures a SQLiteStorage.
type Option func(*SQLiteStorage)

// WithTable sets the name of the table used to store workflow state.
// Default: "workflow_states".
func WithTable(name string) Option {
	return func(s *SQLiteStorage) {
		s.table = name
	}
}

// WithIDColumn sets the name of the column used to store the workflow ID.
// Default: "id".
func WithIDColumn(name string) Option {
	return func(s *SQLiteStorage) {
		s.idColumn = name
	}
}

// WithStateColumn sets the name of the column used to store the workflow's current places (state).
// Default: "state".
func WithStateColumn(name string) Option {
	return func(s *SQLiteStorage) {
		s.stateColumn = name
	}
}

// WithCustomFields defines the schema for additional application-specific data to be stored.
// The map key is the key used in the workflow's context map.
// The map value is the full SQL column definition (e.g., "title TEXT", "amount INTEGER NOT NULL").
func WithCustomFields(fields map[string]string) Option {
	return func(s *SQLiteStorage) {
		s.customFields = fields
	}
}

// NewSQLiteStorage creates a new SQLiteStorage with the given options.
func NewSQLiteStorage(db *sql.DB, opts ...Option) (*SQLiteStorage, error) {
	if db == nil {
		return nil, fmt.Errorf("db cannot be nil")
	}

	s := &SQLiteStorage{
		db:           db,
		table:        "workflow_states",
		idColumn:     "id",
		stateColumn:  "state",
		customFields: make(map[string]string),
	}

	for _, opt := range opts {
		opt(s)
	}

	return s, nil
}

// GenerateSchema returns the `CREATE TABLE` SQL statement based on the storage configuration.
// This allows the user to see, modify, or use the schema with a separate migration tool.
func (s *SQLiteStorage) GenerateSchema() string {
	columns := []string{
		fmt.Sprintf("%s TEXT PRIMARY KEY", s.idColumn),
		fmt.Sprintf("%s TEXT NOT NULL", s.stateColumn),
	}

	for _, colDef := range s.customFields {
		columns = append(columns, colDef)
	}

	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (%s);", s.table, strings.Join(columns, ", "))
}

// Initialize executes the schema generated by GenerateSchema.
// It's a convenience helper for development and testing. For production,
// it's recommended to use a proper migration tool.
func Initialize(db *sql.DB, schema string) error {
	_, err := db.Exec(schema)
	return err
}

// SaveState saves the workflow's current places and any configured custom fields from its context.
func (s *SQLiteStorage) SaveState(ctx context.Context, id string, places []workflow.Place, ctxData map[string]any) error {
	stateJSON, err := json.Marshal(places)
	if err != nil {
		return fmt.Errorf("failed to marshal state: %w", err)
	}

	columns := []string{s.idColumn, s.stateColumn}
	values := []any{id, stateJSON}
	placeholders := []string{"?", "?"}

	for key, colDef := range s.customFields {
		colName := strings.Fields(colDef)[0]
		columns = append(columns, colName)
		placeholders = append(placeholders, "?")

		if val, ok := ctxData[key]; ok {
			// Handle slices and arrays by marshaling to JSON
			// This is needed for fields like "roles" which is []string
			if val != nil {
				// Check if it's a complex type that needs JSON marshaling
				switch value := val.(type) {
				case []string, []any, map[string]any:
					// Marshal slice to JSON
					if jsonBytes, err := json.Marshal(value); err == nil {
						values = append(values, string(jsonBytes))
					} else {
						values = append(values, nil)
					}
				case bool:
					// SQLite doesn't have a native boolean type, convert to integer
					if value {
						values = append(values, 1)
					} else {
						values = append(values, 0)
					}
				default:
					values = append(values, val)
				}
			} else {
				values = append(values, nil)
			}
		} else {
			values = append(values, nil) // Use NULL if key not in context
		}
	}

	// Using "REPLACE INTO" which is a SQLite-specific convenience.
	// It's equivalent to an INSERT or, if a row with the same primary key exists, a DELETE followed by an INSERT.
	query := fmt.Sprintf("REPLACE INTO %s (%s) VALUES (%s);",
		s.table,
		strings.Join(columns, ", "),
		strings.Join(placeholders, ", "),
	)

	_, err = s.db.ExecContext(ctx, query, values...)
	return err
}

// LoadState loads the workflow's places and all configured custom fields into the context map.
func (s *SQLiteStorage) LoadState(ctx context.Context, id string) ([]workflow.Place, map[string]any, error) {
	columns := []string{s.stateColumn}
	customFieldKeys := make([]string, 0, len(s.customFields))

	for key, colDef := range s.customFields {
		colName := strings.Fields(colDef)[0]
		columns = append(columns, colName)
		customFieldKeys = append(customFieldKeys, key)
	}

	query := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ?",
		strings.Join(columns, ", "),
		s.table,
		s.idColumn,
	)

	row := s.db.QueryRowContext(ctx, query, id)

	// Prepare to scan into a slice of any pointers
	scanArgs := make([]any, len(columns))
	for i := range columns {
		scanArgs[i] = new(any)
	}

	err := row.Scan(scanArgs...)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil, fmt.Errorf("%w: id %s", workflow.ErrWorkflowNotFound, id)
		}
		return nil, nil, fmt.Errorf("failed to load state: %w", err)
	}

	// Process results
	var stateJSON []byte
	if rawState, ok := (*scanArgs[0].(*any)).([]byte); ok {
		stateJSON = rawState
	} else {
		return nil, nil, fmt.Errorf("unexpected type for state column")
	}

	var places []workflow.Place
	if err := json.Unmarshal(stateJSON, &places); err != nil {
		return nil, nil, fmt.Errorf("failed to unmarshal state: %w", err)
	}

	context := make(map[string]any)

	for i, key := range customFieldKeys {
		val := *(scanArgs[i+1].(*any))

		// Check if this is a JSON string that should be unmarshaled
		// This handles fields like "roles" (arrays) and "nested" (maps) which are stored as JSON
		if strVal, ok := val.(string); ok && strVal != "" {
			// Try to unmarshal as JSON array first
			var jsonArray []any
			if err := json.Unmarshal([]byte(strVal), &jsonArray); err == nil {
				// Successfully unmarshaled as JSON array
				// Try to convert to []string if all elements are strings
				stringArray := make([]string, 0, len(jsonArray))
				allStrings := true
				for _, item := range jsonArray {
					if str, ok := item.(string); ok {
						stringArray = append(stringArray, str)
					} else {
						allStrings = false
						break
					}
				}
				if allStrings && len(stringArray) > 0 {
					context[key] = stringArray
				} else {
					context[key] = jsonArray
				}
			} else {
				// Try to unmarshal as JSON object (map)
				var jsonMap map[string]any
				if err := json.Unmarshal([]byte(strVal), &jsonMap); err == nil {
					context[key] = jsonMap
				} else {
					// Not JSON, store as string
					context[key] = strVal
				}
			}
		} else if val != nil {
			// SQLite may return int64 for INTEGER columns, etc.
			// Check if this is a boolean stored as integer (1 or 0)
			if intVal, ok := val.(int64); ok {
				// Check if the column definition suggests this is a boolean
				// For now, we'll check if the value is 0 or 1 and the key suggests boolean
				// This is a heuristic - in practice, you'd check the column definition
				if (key == "bool" || key == "boolean") && (intVal == 0 || intVal == 1) {
					context[key] = intVal == 1
				} else {
					context[key] = val
				}
			} else {
				context[key] = val
			}
		} else {
			context[key] = nil
		}
	}

	return places, context, nil
}

// DeleteState removes a workflow's state from the database.
func (s *SQLiteStorage) DeleteState(ctx context.Context, id string) error {
	query := fmt.Sprintf("DELETE FROM %s WHERE %s = ?", s.table, s.idColumn)
	_, err := s.db.ExecContext(ctx, query, id)
	return err
}
