package storage

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/ehabterra/workflow"
)

// SQLiteStorage provides a persistent storage implementation using SQLite.
// It is highly configurable to allow for custom table and column names,
// as well as storing arbitrary application-specific data alongside the
// workflow state. It implements workflow.Storage and workflow.VersionedStorage.
type SQLiteStorage struct {
	db *sql.DB
	config
}

// NewSQLiteStorage creates a new SQLiteStorage with the given options.
func NewSQLiteStorage(db *sql.DB, opts ...Option) (*SQLiteStorage, error) {
	if db == nil {
		return nil, fmt.Errorf("db cannot be nil")
	}

	cfg := defaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}

	return &SQLiteStorage{db: db, config: cfg}, nil
}

// GenerateSchema returns the `CREATE TABLE` SQL statement based on the storage configuration.
// This allows the user to see, modify, or use the schema with a separate migration tool.
func (s *SQLiteStorage) GenerateSchema() string {
	columns := []string{
		fmt.Sprintf("%s TEXT PRIMARY KEY", s.idColumn),
		fmt.Sprintf("%s TEXT NOT NULL", s.stateColumn),
		fmt.Sprintf("%s INTEGER NOT NULL DEFAULT 0", s.versionColumn),
	}
	if s.contextColumn != "" {
		columns = append(columns, fmt.Sprintf("%s TEXT NOT NULL DEFAULT '{}'", s.contextColumn))
	}

	for _, colDef := range s.customFields {
		columns = append(columns, colDef)
	}

	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (%s);", s.table, strings.Join(columns, ", "))
}

// Initialize executes the schema generated by GenerateSchema.
// It's a convenience helper for development and testing. For production,
// it's recommended to use a proper migration tool.
func Initialize(db *sql.DB, schema string) error {
	_, err := db.Exec(schema)
	return err
}

// SaveState saves the workflow's current places and any configured custom fields from its context.
func (s *SQLiteStorage) SaveState(ctx context.Context, id string, marking workflow.Marking, ctxData map[string]any) error {
	return s.saveState(ctx, s.db, id, marking, ctxData)
}

// SaveStateTx behaves like SaveState but writes through the provided transaction,
// so it can be committed atomically with other writes (e.g. a history record).
// See RunInTx.
func (s *SQLiteStorage) SaveStateTx(ctx context.Context, tx *sql.Tx, id string, marking workflow.Marking, ctxData map[string]any) error {
	return s.saveState(ctx, tx, id, marking, ctxData)
}

func (s *SQLiteStorage) saveState(ctx context.Context, q querier, id string, marking workflow.Marking, ctxData map[string]any) error {
	stateJSON, err := json.Marshal(marking)
	if err != nil {
		return fmt.Errorf("failed to marshal state: %w", err)
	}

	columns := []string{s.idColumn, s.stateColumn}
	values := []any{id, stateJSON}
	if s.contextColumn != "" {
		ctxJSON, err := encodeContextJSON(ctxData)
		if err != nil {
			return err
		}
		columns = append(columns, s.contextColumn)
		values = append(values, ctxJSON)
	}
	customCols, customVals := s.customColumns(ctxData, encodeValue)
	columns = append(columns, customCols...)
	values = append(values, customVals...)
	placeholders := make([]string, len(columns))
	for i := range placeholders {
		placeholders[i] = "?"
	}

	// Using "REPLACE INTO" which is a SQLite-specific convenience.
	// It's equivalent to an INSERT or, if a row with the same primary key exists, a DELETE followed by an INSERT.
	query := fmt.Sprintf("REPLACE INTO %s (%s) VALUES (%s);",
		s.table,
		strings.Join(columns, ", "),
		strings.Join(placeholders, ", "),
	)

	_, err = q.ExecContext(ctx, query, values...)
	return err
}

// encodeValue converts a context value into a form SQLite can store. SQLite has
// no native boolean, so bools become 0/1; slices and maps are JSON-encoded.
func encodeValue(val any, present bool) any {
	if !present || val == nil {
		return nil
	}
	switch value := val.(type) {
	case []string, []any, map[string]any:
		if jsonBytes, err := json.Marshal(value); err == nil {
			return string(jsonBytes)
		}
		return nil
	case bool:
		if value {
			return 1
		}
		return 0
	default:
		return val
	}
}

// LoadState loads the workflow's marking and all configured custom fields into the context map.
func (s *SQLiteStorage) LoadState(ctx context.Context, id string) (workflow.Marking, map[string]any, error) {
	return s.loadState(ctx, s.db, id)
}

// LoadStateTx behaves like LoadState but reads through the provided transaction,
// so it observes the transaction's own uncommitted writes.
func (s *SQLiteStorage) LoadStateTx(ctx context.Context, tx *sql.Tx, id string) (workflow.Marking, map[string]any, error) {
	return s.loadState(ctx, tx, id)
}

func (s *SQLiteStorage) loadState(ctx context.Context, q querier, id string) (workflow.Marking, map[string]any, error) {
	columns := []string{s.stateColumn}
	if s.contextColumn != "" {
		columns = append(columns, s.contextColumn)
	}
	customStart := len(columns)
	customFieldKeys := make([]string, 0, len(s.customFields))

	for key, colDef := range s.customFields {
		colName := strings.Fields(colDef)[0]
		columns = append(columns, colName)
		customFieldKeys = append(customFieldKeys, key)
	}

	query := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ?",
		strings.Join(columns, ", "),
		s.table,
		s.idColumn,
	)

	row := q.QueryRowContext(ctx, query, id)

	// Prepare to scan into a slice of any pointers
	scanArgs := make([]any, len(columns))
	for i := range columns {
		scanArgs[i] = new(any)
	}

	err := row.Scan(scanArgs...)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil, fmt.Errorf("%w: id %s", workflow.ErrWorkflowNotFound, id)
		}
		return nil, nil, fmt.Errorf("failed to load state: %w", err)
	}

	// Process results
	var stateJSON []byte
	if rawState, ok := (*scanArgs[0].(*any)).([]byte); ok {
		stateJSON = rawState
	} else {
		return nil, nil, fmt.Errorf("unexpected type for state column")
	}

	marking, err := workflow.UnmarshalMarkingJSON(stateJSON)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to unmarshal state: %w", err)
	}

	// The context column holds the full context map; custom-field columns are
	// queryable projections of individual keys and are overlaid afterwards so
	// their typed values (e.g. INTEGER int64) win over the JSON decoding.
	context := make(map[string]any)
	if s.contextColumn != "" {
		context, err = decodeContextJSON(*(scanArgs[1].(*any)))
		if err != nil {
			return nil, nil, err
		}
	}

	for i, key := range customFieldKeys {
		val := *(scanArgs[customStart+i].(*any))

		// Check if this is a JSON string that should be unmarshaled
		// This handles fields like "roles" (arrays) and "nested" (maps) which are stored as JSON
		if strVal, ok := val.(string); ok && strVal != "" {
			// Try to unmarshal as JSON array first
			var jsonArray []any
			if err := json.Unmarshal([]byte(strVal), &jsonArray); err == nil {
				// Successfully unmarshaled as JSON array
				// Try to convert to []string if all elements are strings
				stringArray := make([]string, 0, len(jsonArray))
				allStrings := true
				for _, item := range jsonArray {
					if str, ok := item.(string); ok {
						stringArray = append(stringArray, str)
					} else {
						allStrings = false
						break
					}
				}
				if allStrings && len(stringArray) > 0 {
					context[key] = stringArray
				} else {
					context[key] = jsonArray
				}
			} else {
				// Try to unmarshal as JSON object (map)
				var jsonMap map[string]any
				if err := json.Unmarshal([]byte(strVal), &jsonMap); err == nil {
					context[key] = jsonMap
				} else {
					// Not JSON, store as string
					context[key] = strVal
				}
			}
		} else if val != nil {
			// SQLite may return int64 for INTEGER columns, etc.
			// Check if this is a boolean stored as integer (1 or 0)
			if intVal, ok := val.(int64); ok {
				// Check if the column definition suggests this is a boolean
				// For now, we'll check if the value is 0 or 1 and the key suggests boolean
				// This is a heuristic - in practice, you'd check the column definition
				if (key == "bool" || key == "boolean") && (intVal == 0 || intVal == 1) {
					context[key] = intVal == 1
				} else {
					context[key] = val
				}
			} else {
				context[key] = val
			}
		} else {
			context[key] = nil
		}
	}

	return marking, context, nil
}

// ListIDs implements workflow.ListableStorage, returning persisted workflow IDs
// ordered by ID for stable pagination. A zero opts.Limit means no limit.
func (s *SQLiteStorage) ListIDs(ctx context.Context, opts workflow.ListOptions) ([]string, error) {
	query := fmt.Sprintf("SELECT %s FROM %s ORDER BY %s", s.idColumn, s.table, s.idColumn)
	var args []any
	if opts.Limit > 0 {
		query += " LIMIT ? OFFSET ?"
		args = append(args, opts.Limit, opts.Offset)
	} else if opts.Offset > 0 {
		query += " LIMIT -1 OFFSET ?" // SQLite requires a LIMIT before OFFSET
		args = append(args, opts.Offset)
	}
	return scanIDs(s.db.QueryContext(ctx, query, args...))
}

// DeleteState removes a workflow's state from the database.
func (s *SQLiteStorage) DeleteState(ctx context.Context, id string) error {
	return s.deleteState(ctx, s.db, id)
}

// DeleteStateTx behaves like DeleteState but writes through the provided transaction.
func (s *SQLiteStorage) DeleteStateTx(ctx context.Context, tx *sql.Tx, id string) error {
	return s.deleteState(ctx, tx, id)
}

func (s *SQLiteStorage) deleteState(ctx context.Context, q querier, id string) error {
	query := fmt.Sprintf("DELETE FROM %s WHERE %s = ?", s.table, s.idColumn)
	_, err := q.ExecContext(ctx, query, id)
	return err
}

// LoadVersionedState implements workflow.VersionedStorage. It loads the workflow's
// marking and context data along with its current optimistic-concurrency version.
// A never-saved workflow returns workflow.ErrWorkflowNotFound.
func (s *SQLiteStorage) LoadVersionedState(ctx context.Context, id string) (workflow.Marking, map[string]any, int64, error) {
	marking, ctxData, err := s.loadState(ctx, s.db, id)
	if err != nil {
		return nil, nil, 0, err
	}

	var version int64
	query := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ?", s.versionColumn, s.table, s.idColumn)
	if err := s.db.QueryRowContext(ctx, query, id).Scan(&version); err != nil {
		return nil, nil, 0, fmt.Errorf("failed to load version: %w", err)
	}
	return marking, ctxData, version, nil
}

// SaveVersionedState implements workflow.VersionedStorage. It saves the workflow
// only if the stored version equals expectedVersion, returning the new version.
// Pass expectedVersion 0 to create a new workflow. A mismatch returns
// workflow.ErrConflict.
func (s *SQLiteStorage) SaveVersionedState(ctx context.Context, id string, marking workflow.Marking, ctxData map[string]any, expectedVersion int64) (int64, error) {
	return s.saveVersionedState(ctx, s.db, id, marking, ctxData, expectedVersion)
}

// SaveVersionedStateTx behaves like SaveVersionedState but writes through the
// provided transaction, so a versioned state change and a history record can be
// committed atomically. See RunInTx.
func (s *SQLiteStorage) SaveVersionedStateTx(ctx context.Context, tx *sql.Tx, id string, marking workflow.Marking, ctxData map[string]any, expectedVersion int64) (int64, error) {
	return s.saveVersionedState(ctx, tx, id, marking, ctxData, expectedVersion)
}

func (s *SQLiteStorage) saveVersionedState(ctx context.Context, q querier, id string, marking workflow.Marking, ctxData map[string]any, expectedVersion int64) (int64, error) {
	stateJSON, err := json.Marshal(marking)
	if err != nil {
		return 0, fmt.Errorf("failed to marshal state: %w", err)
	}
	customCols, customVals := s.customColumns(ctxData, encodeValue)
	if s.contextColumn != "" {
		ctxJSON, err := encodeContextJSON(ctxData)
		if err != nil {
			return 0, err
		}
		customCols = append([]string{s.contextColumn}, customCols...)
		customVals = append([]any{ctxJSON}, customVals...)
	}

	if expectedVersion <= 0 {
		// Create a new row at version 1; do nothing if the id already exists so we
		// can distinguish "created" (1 row affected) from "already exists" (0).
		columns := append([]string{s.idColumn, s.stateColumn, s.versionColumn}, customCols...)
		values := append([]any{id, stateJSON, int64(1)}, customVals...)
		placeholders := make([]string, len(columns))
		for i := range placeholders {
			placeholders[i] = "?"
		}
		query := fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s) ON CONFLICT(%s) DO NOTHING;",
			s.table, strings.Join(columns, ", "), strings.Join(placeholders, ", "), s.idColumn)

		res, err := q.ExecContext(ctx, query, values...)
		if err != nil {
			return 0, err
		}
		n, err := res.RowsAffected()
		if err != nil {
			return 0, err
		}
		if n == 0 {
			return 0, fmt.Errorf("%w: workflow %s already exists (expected version 0)", workflow.ErrConflict, id)
		}
		return 1, nil
	}

	// Update the existing row only if its version still matches, bumping the version.
	setClauses := []string{
		fmt.Sprintf("%s = ?", s.stateColumn),
		fmt.Sprintf("%s = %s + 1", s.versionColumn, s.versionColumn),
	}
	args := []any{stateJSON}
	for i, col := range customCols {
		setClauses = append(setClauses, fmt.Sprintf("%s = ?", col))
		args = append(args, customVals[i])
	}
	args = append(args, id, expectedVersion)

	query := fmt.Sprintf("UPDATE %s SET %s WHERE %s = ? AND %s = ?;",
		s.table, strings.Join(setClauses, ", "), s.idColumn, s.versionColumn)

	res, err := q.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	if n == 0 {
		return 0, fmt.Errorf("%w: workflow %s (expected version %d)", workflow.ErrConflict, id, expectedVersion)
	}
	return expectedVersion + 1, nil
}
